# Some tips in learning R
Using “Learning R" to know more about R language

## Chaper 3: Variable

Q1: 数字的三个内置类的名称是什么?  
A1: numeric, integer, complex  
  
Q2: 如何把字符串“6.283185”转换为数字?  
A2: 

In [3]:
num = '6.283185'
as(num, 'numeric')

[1] 6.283185

Q3: 查找以下值 Inf、NA、NaN 和 "" 的类、类型、模式及存储模式  
A3: 

In [4]:
print(class(Inf))
print(class(NA))
print(class(NaN))
print(class(""))

[1] "numeric"
[1] "logical"
[1] "numeric"
[1] "character"


In [5]:
print(typeof(Inf))
print(typeof(NA))
print(typeof(NaN))
print(typeof(""))

[1] "double"
[1] "logical"
[1] "double"
[1] "character"


In [6]:
print(mode(Inf))
print(mode(NA))
print(mode(NaN))
print(mode(""))

[1] "numeric"
[1] "logical"
[1] "numeric"
[1] "character"


In [7]:
print(storage.mode(Inf))
print(storage.mode(NA))
print(storage.mode(NaN))
print(storage.mode(""))

[1] "double"
[1] "logical"
[1] "double"
[1] "character"


Q4: 随机从“dog”、“cat”、“hamster”和“goldfish”中以相等的概率生成 1000 个宠物名。 显示所得变量的前几个值，并计算每种宠物的数量。  
A4:

In [22]:
animal = factor(c("dog", "cat", "hamster", "goldfish"))
# animals = as(sample(animal, 1000, replace = TRUE), 'factor')
animals = sample(animal, 1000, replace = TRUE)
print(head(animals))
print(summary(animals))

[1] cat     dog     cat     dog     hamster cat    
Levels: cat dog goldfish hamster
     cat      dog goldfish  hamster 
     269      237      245      249 


## Chaper 4: Vector, Array, Matrix

In [26]:
8.5:4.5

[1] 8.5 7.5 6.5 5.5 4.5

In [27]:
vector("numeric", 5)

[1] 0 0 0 0 0

In [28]:
seq.int(3, 12, 2)

[1]  3  5  7  9 11

In [29]:
seq.int(0.1, 0.01, -0.01)

[1] 0.10 0.09 0.08 0.07 0.06 0.05 0.04 0.03 0.02 0.01

In [32]:
n = 10
seq_len(n)

[1]  1  2  3  4  5  6  7  8  9 10

In [33]:
pp = c("Peter", "Piper", "picked", "a", "peck", "of", "pickled", "peppers")
for(i in seq_along(pp)) print(pp[i])

[1] "Peter"
[1] "Piper"
[1] "picked"
[1] "a"
[1] "peck"
[1] "of"
[1] "pickled"
[1] "peppers"


### length

In [34]:
sn <- c("Sheena", "leads", "Sheila", "needs")
print(length(sn))
print(nchar(sn))

[1] 4
[1] 6 5 6 5


In [35]:
poincare <- c(1, 0, 0, 0, 2, 0, 2, 0)
length(poincare) = 4
poincare

[1] 1 0 0 0

In [36]:
length(poincare) = 8
poincare

[1]  1  0  0  0 NA NA NA NA

### names

In [38]:
c(apple = 1, banana = 2, "kiwi fruit" = 3, 4)

apple     banana kiwi fruit            
         1          2          3          4

In [40]:
x <- 1:4
names(x) <- c("apple", "bananas", "kiwi fruit", "")
x

apple    bananas kiwi fruit            
         1          2          3          4

### index

In [50]:
x <- (-6:5) ^ 2
x[c(1, 3, 5)]

[1] 36 16  4

In [51]:
which(x > 10)

[1]  1  2  3 11 12

In [53]:
which.max(x)  ## return argmax index

[1] 1

### loop and rep in vector

In [54]:
rep(1:5, 3)

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

In [55]:
rep(1:5, each = 3)

[1] 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5

In [56]:
rep(1:5, times = 1:5)

[1] 1 2 2 3 3 3 4 4 4 4 5 5 5 5 5

In [57]:
rep(1:5, length.out = 7)

[1] 1 2 3 4 5 1 2

In [58]:
rep.int(1:5, 3)

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

In [59]:
rep_len(1:5, 13)

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3

### Array and Matrix

创建数组

In [64]:
three_d_array = array(
    1:24, 
    dim = c(4,3,2),
    dimnames = list(
        c("one", "two", "three", "four"),
        c("ein", "zwei", "drei"),
        c("un", "deux")
    )
)
three_d_array

, , un

      ein zwei drei
one     1    5    9
two     2    6   10
three   3    7   11
four    4    8   12

, , deux

      ein zwei drei
one    13   17   21
two    14   18   22
three  15   19   23
four   16   20   24

In [69]:
a_matrix = matrix(
    1:12,
    nrow = 4, 
    dimnames = list(
        c("one", "two", "three", "four"),
        c("ein", "zwei", "drei")
    )
)
a_matrix

ein zwei drei
one   1   5     9  
two   2   6    10  
three 3   7    11  
four  4   8    12

In [70]:
print(dim(three_d_array))
print(dim(a_matrix))

[1] 4 3 2
[1] 4 3


In [72]:
print(nrow(three_d_array))
print(ncol(three_d_array))

[1] 4
[1] 3


In [73]:
m <- matrix(c(1, 0, 1, 5, -3, 1, 2, 4, 7), nrow = 3)
m

[,1] [,2] [,3]
[1,] 1     5   2   
[2,] 0    -3   4   
[3,] 1     1   7

In [74]:
m ^ -1

[,1] [,2]       [,3]     
[1,]   1   0.2000000 0.5000000
[2,] Inf  -0.3333333 0.2500000
[3,]   1   1.0000000 0.1428571

In [75]:
inverse_of_m = solve(m)
inverse_of_m

[,1] [,2] [,3]
[1,] -25  -33  26  
[2,]   4    5  -4  
[3,]   3    4  -3

In [77]:
m %*% solve(m)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

### QA
Q1: 四种向量索引方式  
A1:  
 - 给向量传入正数
 - 给向量传入负数
 - 给向量传入逻辑向量
 - 对于已命名的向量，给向量传入命名的字符向量
 
Q2: 第 n 个三角形数表示为 n * (n + 1) / 2。创建一个包含前 20 个三角形数的序列。R 有 一个内置常数 letters，它包含小写的罗马字母。使用前 20 个英文字母来给你刚刚创 建的向量命名。选择命名为元音的三角数。  
A2:  

In [86]:
idx = 1:20
tri_numbers = idx * (idx + 1) / 2
names(tri_numbers) = letters[1:20]
tri_numbers

a   b   c   d   e   f   g   h   i   j   k   l   m   n   o   p   q   r   s   t 
  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171 190 210

Q3: diag 函数有几种用途，其中之一是以输入向量作为对角线来创建一个方阵。使用序列 10 到 0 到 11(即 11,10,...,1,0,1,...,11)创建一个 21×21 的矩阵。  
A3: 

In [112]:
center = diag(c(10:1, 0:10))
center

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   0    0    0    0    0    0    0    0    0     ...   0     0    
 [2,]  0   9    0    0    0    0    0    0    0    0     ...   0     0    
 [3,]  0   0    8    0    0    0    0    0    0    0     ...   0     0    
 [4,]  0   0    0    7    0    0    0    0    0    0     ...   0     0    
 [5,]  0   0    0    0    6    0    0    0    0    0     ...   0     0    
 [6,]  0   0    0    0    0    5    0    0    0    0     ...   0     0    
 [7,]  0   0    0    0    0    0    4    0    0    0     ...   0     0    
 [8,]  0   0    0    0    0    0    0    3    0    0     ...   0     0    
 [9,]  0   0    0    0    0    0    0    0    2    0     ...   0     0    
[10,]  0   0    0    0    0    0    0    0    0    1     ...   0     0    
[11,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ...   1     0    
[13,]  0   0    0    0    0    0    0    0    0    0     ...   0     2    
[14,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[15,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0      0   
 [2,] 0     0     0     0     0     0     0      0   
 [3,] 0     0     0     0     0     0     0      0   
 [4,] 0     0     0     0     0     0     0      0   
 [5,] 0     0     0     0     0     0     0      0   
 [6,] 0     0     0     0     0     0     0      0   
 [7,] 0     0     0     0     0     0     0      0   
 [8,] 0     0     0     0     0     0     0      0   
 [9,] 0     0     0     0     0     0     0      0   
[10,] 0     0     0     0     0     0     0      0   
[11,] 0     0     0     0     0     0     0      0   
[12,] 0     0     0     0     0     0     0      0   
[13,] 0     0     0     0     0     0     0      0   
[14,] 3     0     0     0     0     0     0      0   
[15,] 0     4     0     0     0     0     0      0   
[16,] 0     0     5     0     0     0     0      0   
[17,] 0     0     0     6     0     0     0      0   
[18,] 0     0     0     0     7     0     0      0   
[19,] 0     0     0     0     0     8     0      0   
[20,] 0     0     0     0     0     0     9      0   
[21,] 0     0     0     0     0     0     0     10

Q4: 你可通过给 diag 函数传递两个额外的参数来指定输出的维度。创建一个主对角线元素 都为 1 的 20×21 的矩阵。现在，在此矩阵之上加一行全零元素来创建一个 21×21 的方 阵，原来主对角线上的全 1 元素现在全体向下偏移一行。  
A4:  

In [113]:
num_row = 21

In [116]:
t = diag(1, num_row-1, num_row)

In [117]:
low = rbind(rep(0, num_row), t)


In [118]:
high = cbind(rep(0, num_row), diag(1, num_row, num_row-1))

In [119]:
wilkinson = low + center + high
wilkinson

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   1    0    0    0    0    0    0    0    0     ...   0     0    
 [2,]  1   9    1    0    0    0    0    0    0    0     ...   0     0    
 [3,]  0   1    8    1    0    0    0    0    0    0     ...   0     0    
 [4,]  0   0    1    7    1    0    0    0    0    0     ...   0     0    
 [5,]  0   0    0    1    6    1    0    0    0    0     ...   0     0    
 [6,]  0   0    0    0    1    5    1    0    0    0     ...   0     0    
 [7,]  0   0    0    0    0    1    4    1    0    0     ...   0     0    
 [8,]  0   0    0    0    0    0    1    3    1    0     ...   0     0    
 [9,]  0   0    0    0    0    0    0    1    2    1     ...   0     0    
[10,]  0   0    0    0    0    0    0    0    1    1     ...   0     0    
[11,]  0   0    0    0    0    0    0    0    0    1     ...   1     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ...   1     1    
[13,]  0   0    0    0    0    0    0    0    0    0     ...   1     2    
[14,]  0   0    0    0    0    0    0    0    0    0     ...   0     1    
[15,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0      0   
 [2,] 0     0     0     0     0     0     0      0   
 [3,] 0     0     0     0     0     0     0      0   
 [4,] 0     0     0     0     0     0     0      0   
 [5,] 0     0     0     0     0     0     0      0   
 [6,] 0     0     0     0     0     0     0      0   
 [7,] 0     0     0     0     0     0     0      0   
 [8,] 0     0     0     0     0     0     0      0   
 [9,] 0     0     0     0     0     0     0      0   
[10,] 0     0     0     0     0     0     0      0   
[11,] 0     0     0     0     0     0     0      0   
[12,] 0     0     0     0     0     0     0      0   
[13,] 1     0     0     0     0     0     0      0   
[14,] 3     1     0     0     0     0     0      0   
[15,] 1     4     1     0     0     0     0      0   
[16,] 0     1     5     1     0     0     0      0   
[17,] 0     0     1     6     1     0     0      0   
[18,] 0     0     0     1     7     1     0      0   
[19,] 0     0     0     0     1     8     1      0   
[20,] 0     0     0     0     0     1     9      1   
[21,] 0     0     0     0     0     0     1     10

In [120]:
eigen(wilkinson)

eigen() decomposition
$values
 [1] 10.7461942 10.7461942  9.2106786  9.2106786  8.0389411  8.0389411
 [7]  7.0039522  7.0039518  6.0002340  6.0002175  5.0002444  4.9997825
[13]  4.0043540  3.9960482  3.0430993  2.9610589  2.1302092  1.7893214
[19]  0.9475344  0.2538058 -1.1254415

$vectors
              [,1]          [,2]          [,3]          [,4]          [,5]
 [1,] 5.495410e-01 -5.493073e-01 -3.824805e-01  3.824543e-01  2.111086e-01
 [2,] 4.100643e-01 -4.098899e-01  3.019000e-01 -3.018793e-01 -4.139963e-01
 [3,] 1.665109e-01 -1.664401e-01  4.460844e-01 -4.460538e-01  1.867663e-01
 [4,] 4.720694e-02 -4.718686e-02  2.381648e-01 -2.381485e-01  4.212692e-01
 [5,] 1.033548e-02 -1.033109e-02  8.042149e-02 -8.041598e-02  2.509076e-01
 [6,] 1.847263e-03 -1.846477e-03  2.004275e-02 -2.004137e-02  9.031667e-02
 [7,] 2.792477e-04 -2.791289e-04  3.972068e-03 -3.971794e-03  2.355942e-02
 [8,] 3.659637e-05 -3.658067e-05  6.544258e-04 -6.543736e-04  4.838449e-03
 [9,] 4.234910e-06 -4.232115e-06  

## Chapter 5: List and DataFrame
### List

In [5]:
a_list = list(
    c(1,1,2,5,14,42),
    month.abb,
    matrix(c(8, -3, 1, 3), nrow = 2),
    asin
)
a_list

[[1]]
[1]  1  1  2  5 14 42

[[2]]
 [1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

[[3]]
     [,1] [,2]
[1,]    8    1
[2,]   -3    3

[[4]]
function (x)  .Primitive("asin")

In [6]:
names(a_list) = c("catalan", "months", "involutary", "arcsin")
a_list

$catalan
[1]  1  1  2  5 14 42

$months
 [1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

$involutary
     [,1] [,2]
[1,]    8    1
[2,]   -3    3

$arcsin
function (x)  .Primitive("asin")

####  Atomic and Recursive
 Atomic variable is a variable that can't include itself;  
 On the contrast, recursive variable is a variable that can include itself.

In [7]:
is.atomic(list())

[1] FALSE

In [8]:
is.recursive(list())

[1] TRUE

In [9]:
is.atomic(numeric())

[1] TRUE

In [10]:
is.recursive(numeric())

[1] FALSE

#### Dimension and calculate

In [11]:
length(a_list)

[1] 4

In [14]:
l1 = list(1:5)
l2 = list(6:10)
l1[[1]] + l2[[1]]  ## equal to 1:5 + 6:10

[1]  7  9 11 13 15

In [17]:
l = list(
    first = 1,
    second = 2,
    third = list(
        alpha = 3.1,
        beta = 3,2
    )
)
l

$first
[1] 1

$second
[1] 2

$third
$third$alpha
[1] 3.1

$third$beta
[1] 3

$third[[3]]
[1] 2

In [20]:
print(l[1:2])
print('----------------------------------------')
print(l[-3])
print('----------------------------------------')
print(l[c('first', 'second')])
print('----------------------------------------')
print(l[c(TRUE, TRUE, FALSE)])

$first
[1] 1

$second
[1] 2

[1] "----------------------------------------"
$first
[1] 1

$second
[1] 2

[1] "----------------------------------------"
$first
[1] 1

$second
[1] 2

[1] "----------------------------------------"
$first
[1] 1

$second
[1] 2



#### Convert of vector and list

In [21]:
busy_behaver = c(1, 6, 21, 107)
as.list(busy_behaver)

[[1]]
[1] 1

[[2]]
[1] 6

[[3]]
[1] 21

[[4]]
[1] 107

In [22]:
as.numeric(list(1, 6, 21, 107))

[1]   1   6  21 107

#### Combine list

In [23]:
c(list(a = 1, b = 2), list(3))

$a
[1] 1

$b
[1] 2

[[3]]
[1] 3

#### NULL and NA

In [25]:
print(length(NULL))
print(length(NA))

[1] 0
[1] 1


#### Pairlists

In [27]:
arguments_of_sd = formals(sd)
arguments_of_sd

$x


$na.rm
[1] FALSE


In [28]:
class(arguments_of_sd)

[1] "pairlist"

### DataFrame

In [29]:
a_df = data.frame(
    x = letters[1:5],
    y = rnorm(5),
    z = runif(5) > 0.5
)
a_df

x y          z    
1 a  0.3150092 FALSE
2 b -0.1904853 FALSE
3 c  1.3861771  TRUE
4 d  0.9775685  TRUE
5 e  0.1780399 FALSE

In [34]:
rownames(a_df) = month.name[1:5]
a_df

x y          z    
January  a  0.3150092 FALSE
February b -0.1904853 FALSE
March    c  1.3861771  TRUE
April    d  0.9775685  TRUE
May      e  0.1780399 FALSE

In [35]:
row.names(a_df)

[1] "January"  "February" "March"    "April"    "May"

In [36]:
rownames(a_df)

[1] "January"  "February" "March"    "April"    "May"

In [37]:
row.names(a_df) == rownames(a_df)

[1] TRUE TRUE TRUE TRUE TRUE

#### index data.frame

In [38]:
a_df[2:3, -3]

x y         
February b -0.1904853
March    c  1.3861771

In [39]:
a_df[c(FALSE, TRUE, TRUE, FALSE, FALSE), c("x", "y")]

x y         
February b -0.1904853
March    c  1.3861771

In [41]:
a_df[a_df$y >0 | a_df$z, "x"]

[1] a c d e
Levels: a b c d e

In [42]:
subset(a_df, y>0|z, x)

x
January a
March   c
April   d
May     e

#### Operation of data.frame

In [43]:
t(a_df)

January    February   March      April      May       
x a          b          c          d          e         
y  0.3150092 -0.1904853  1.3861771  0.9775685  0.1780399
z FALSE      FALSE      TRUE       TRUE       FALSE

In [44]:
colSums(a_df[, 2:3])

y        z 
2.666309 2.000000

In [45]:
colMeans(a_df[, 2:3])

y         z 
0.5332619 0.4000000

#### home work

In [47]:
iris_numeric = iris[-5]
print(head(iris_numeric))
colMeans(iris_numeric)

  Sepal.Length Sepal.Width Petal.Length Petal.Width
1          5.1         3.5          1.4         0.2
2          4.9         3.0          1.4         0.2
3          4.7         3.2          1.3         0.2
4          4.6         3.1          1.5         0.2
5          5.0         3.6          1.4         0.2
6          5.4         3.9          1.7         0.4


Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    5.843333     3.057333     3.758000     1.199333

In [59]:
beaver_1 = cbind(beaver1, rep(1, dim(beaver1)[1]))
names(beaver_1) = c(names(beaver1), 'ID')
beaver_2 = cbind(beaver2, rep(2, dim(beaver2)[1]))
names(beaver_2) = c(names(beaver2), 'ID')
beaver = rbind(beaver_1, beaver_2)
print(head(beaver))
beaver_active = subset(beaver, activ == 1)
print(beaver_active)

  day time  temp activ ID
1 346  840 36.33     0  1
2 346  850 36.34     0  1
3 346  900 36.35     0  1
4 346  910 36.42     0  1
5 346  920 36.55     0  1
6 346  930 36.69     0  1
    day time  temp activ ID
54  346 1730 37.07     1  1
68  346 1950 37.10     1  1
80  346 2150 37.53     1  1
83  346 2230 37.25     1  1
86  346 2300 37.24     1  1
114 347  340 37.15     1  1
153 307 1550 37.98     1  2
154 307 1600 38.02     1  2
155 307 1610 38.00     1  2
156 307 1620 38.24     1  2
157 307 1630 38.10     1  2
158 307 1640 38.24     1  2
159 307 1650 38.11     1  2
160 307 1700 38.02     1  2
161 307 1710 38.11     1  2
162 307 1720 38.01     1  2
163 307 1730 37.91     1  2
164 307 1740 37.96     1  2
165 307 1750 38.03     1  2
166 307 1800 38.17     1  2
167 307 1810 38.19     1  2
168 307 1820 38.18     1  2
169 307 1830 38.15     1  2
170 307 1840 38.04     1  2
171 307 1850 37.96     1  2
172 307 1900 37.84     1  2
173 307 1910 37.83     1  2
174 307 1920 37.84     1  2
175 30