# Some tips in learning R
Using “Learning R" to know more about R language

## Chaper 3: Variable

Q1: 数字的三个内置类的名称是什么?  
A1: numeric, integer, complex  
  
Q2: 如何把字符串“6.283185”转换为数字?  
A2: 

In [3]:
num = '6.283185'
as(num, 'numeric')

[1] 6.283185

Q3: 查找以下值 Inf、NA、NaN 和 "" 的类、类型、模式及存储模式  
A3: 

In [4]:
print(class(Inf))
print(class(NA))
print(class(NaN))
print(class(""))

[1] "numeric"
[1] "logical"
[1] "numeric"
[1] "character"


In [5]:
print(typeof(Inf))
print(typeof(NA))
print(typeof(NaN))
print(typeof(""))

[1] "double"
[1] "logical"
[1] "double"
[1] "character"


In [6]:
print(mode(Inf))
print(mode(NA))
print(mode(NaN))
print(mode(""))

[1] "numeric"
[1] "logical"
[1] "numeric"
[1] "character"


In [7]:
print(storage.mode(Inf))
print(storage.mode(NA))
print(storage.mode(NaN))
print(storage.mode(""))

[1] "double"
[1] "logical"
[1] "double"
[1] "character"


Q4: 随机从“dog”、“cat”、“hamster”和“goldfish”中以相等的概率生成 1000 个宠物名。 显示所得变量的前几个值，并计算每种宠物的数量。  
A4:

In [22]:
animal = factor(c("dog", "cat", "hamster", "goldfish"))
# animals = as(sample(animal, 1000, replace = TRUE), 'factor')
animals = sample(animal, 1000, replace = TRUE)
print(head(animals))
print(summary(animals))

[1] cat     dog     cat     dog     hamster cat    
Levels: cat dog goldfish hamster
     cat      dog goldfish  hamster 
     269      237      245      249 


## Chaper 4: Vector, Array, Matrix

In [26]:
8.5:4.5

[1] 8.5 7.5 6.5 5.5 4.5

In [27]:
vector("numeric", 5)

[1] 0 0 0 0 0

In [28]:
seq.int(3, 12, 2)

[1]  3  5  7  9 11

In [29]:
seq.int(0.1, 0.01, -0.01)

[1] 0.10 0.09 0.08 0.07 0.06 0.05 0.04 0.03 0.02 0.01

In [32]:
n = 10
seq_len(n)

[1]  1  2  3  4  5  6  7  8  9 10

In [33]:
pp = c("Peter", "Piper", "picked", "a", "peck", "of", "pickled", "peppers")
for(i in seq_along(pp)) print(pp[i])

[1] "Peter"
[1] "Piper"
[1] "picked"
[1] "a"
[1] "peck"
[1] "of"
[1] "pickled"
[1] "peppers"


### length

In [34]:
sn <- c("Sheena", "leads", "Sheila", "needs")
print(length(sn))
print(nchar(sn))

[1] 4
[1] 6 5 6 5


In [35]:
poincare <- c(1, 0, 0, 0, 2, 0, 2, 0)
length(poincare) = 4
poincare

[1] 1 0 0 0

In [36]:
length(poincare) = 8
poincare

[1]  1  0  0  0 NA NA NA NA

### names

In [38]:
c(apple = 1, banana = 2, "kiwi fruit" = 3, 4)

apple     banana kiwi fruit            
         1          2          3          4

In [40]:
x <- 1:4
names(x) <- c("apple", "bananas", "kiwi fruit", "")
x

apple    bananas kiwi fruit            
         1          2          3          4

### index

In [50]:
x <- (-6:5) ^ 2
x[c(1, 3, 5)]

[1] 36 16  4

In [51]:
which(x > 10)

[1]  1  2  3 11 12

In [53]:
which.max(x)  ## return argmax index

[1] 1

### loop and rep in vector

In [54]:
rep(1:5, 3)

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

In [55]:
rep(1:5, each = 3)

[1] 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5

In [56]:
rep(1:5, times = 1:5)

[1] 1 2 2 3 3 3 4 4 4 4 5 5 5 5 5

In [57]:
rep(1:5, length.out = 7)

[1] 1 2 3 4 5 1 2

In [58]:
rep.int(1:5, 3)

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

In [59]:
rep_len(1:5, 13)

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3

### Array and Matrix

创建数组

In [64]:
three_d_array = array(
    1:24, 
    dim = c(4,3,2),
    dimnames = list(
        c("one", "two", "three", "four"),
        c("ein", "zwei", "drei"),
        c("un", "deux")
    )
)
three_d_array

, , un

      ein zwei drei
one     1    5    9
two     2    6   10
three   3    7   11
four    4    8   12

, , deux

      ein zwei drei
one    13   17   21
two    14   18   22
three  15   19   23
four   16   20   24

In [69]:
a_matrix = matrix(
    1:12,
    nrow = 4, 
    dimnames = list(
        c("one", "two", "three", "four"),
        c("ein", "zwei", "drei")
    )
)
a_matrix

ein zwei drei
one   1   5     9  
two   2   6    10  
three 3   7    11  
four  4   8    12

In [70]:
print(dim(three_d_array))
print(dim(a_matrix))

[1] 4 3 2
[1] 4 3


In [72]:
print(nrow(three_d_array))
print(ncol(three_d_array))

[1] 4
[1] 3


In [73]:
m <- matrix(c(1, 0, 1, 5, -3, 1, 2, 4, 7), nrow = 3)
m

[,1] [,2] [,3]
[1,] 1     5   2   
[2,] 0    -3   4   
[3,] 1     1   7

In [74]:
m ^ -1

[,1] [,2]       [,3]     
[1,]   1   0.2000000 0.5000000
[2,] Inf  -0.3333333 0.2500000
[3,]   1   1.0000000 0.1428571

In [75]:
inverse_of_m = solve(m)
inverse_of_m

[,1] [,2] [,3]
[1,] -25  -33  26  
[2,]   4    5  -4  
[3,]   3    4  -3

In [77]:
m %*% solve(m)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

### QA
Q1: 四种向量索引方式  
A1:  
 - 给向量传入正数
 - 给向量传入负数
 - 给向量传入逻辑向量
 - 对于已命名的向量，给向量传入命名的字符向量
 
Q2: 第 n 个三角形数表示为 n * (n + 1) / 2。创建一个包含前 20 个三角形数的序列。R 有 一个内置常数 letters，它包含小写的罗马字母。使用前 20 个英文字母来给你刚刚创 建的向量命名。选择命名为元音的三角数。  
A2:  

In [86]:
idx = 1:20
tri_numbers = idx * (idx + 1) / 2
names(tri_numbers) = letters[1:20]
tri_numbers

a   b   c   d   e   f   g   h   i   j   k   l   m   n   o   p   q   r   s   t 
  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171 190 210

Q3: diag 函数有几种用途，其中之一是以输入向量作为对角线来创建一个方阵。使用序列 10 到 0 到 11(即 11,10,...,1,0,1,...,11)创建一个 21×21 的矩阵。  
A3: 

In [112]:
center = diag(c(10:1, 0:10))
center

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   0    0    0    0    0    0    0    0    0     ...   0     0    
 [2,]  0   9    0    0    0    0    0    0    0    0     ...   0     0    
 [3,]  0   0    8    0    0    0    0    0    0    0     ...   0     0    
 [4,]  0   0    0    7    0    0    0    0    0    0     ...   0     0    
 [5,]  0   0    0    0    6    0    0    0    0    0     ...   0     0    
 [6,]  0   0    0    0    0    5    0    0    0    0     ...   0     0    
 [7,]  0   0    0    0    0    0    4    0    0    0     ...   0     0    
 [8,]  0   0    0    0    0    0    0    3    0    0     ...   0     0    
 [9,]  0   0    0    0    0    0    0    0    2    0     ...   0     0    
[10,]  0   0    0    0    0    0    0    0    0    1     ...   0     0    
[11,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ...   1     0    
[13,]  0   0    0    0    0    0    0    0    0    0     ...   0     2    
[14,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[15,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0      0   
 [2,] 0     0     0     0     0     0     0      0   
 [3,] 0     0     0     0     0     0     0      0   
 [4,] 0     0     0     0     0     0     0      0   
 [5,] 0     0     0     0     0     0     0      0   
 [6,] 0     0     0     0     0     0     0      0   
 [7,] 0     0     0     0     0     0     0      0   
 [8,] 0     0     0     0     0     0     0      0   
 [9,] 0     0     0     0     0     0     0      0   
[10,] 0     0     0     0     0     0     0      0   
[11,] 0     0     0     0     0     0     0      0   
[12,] 0     0     0     0     0     0     0      0   
[13,] 0     0     0     0     0     0     0      0   
[14,] 3     0     0     0     0     0     0      0   
[15,] 0     4     0     0     0     0     0      0   
[16,] 0     0     5     0     0     0     0      0   
[17,] 0     0     0     6     0     0     0      0   
[18,] 0     0     0     0     7     0     0      0   
[19,] 0     0     0     0     0     8     0      0   
[20,] 0     0     0     0     0     0     9      0   
[21,] 0     0     0     0     0     0     0     10

Q4: 你可通过给 diag 函数传递两个额外的参数来指定输出的维度。创建一个主对角线元素 都为 1 的 20×21 的矩阵。现在，在此矩阵之上加一行全零元素来创建一个 21×21 的方 阵，原来主对角线上的全 1 元素现在全体向下偏移一行。  
A4:  

In [113]:
num_row = 21

In [116]:
t = diag(1, num_row-1, num_row)

In [117]:
low = rbind(rep(0, num_row), t)


In [118]:
high = cbind(rep(0, num_row), diag(1, num_row, num_row-1))

In [119]:
wilkinson = low + center + high
wilkinson

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   1    0    0    0    0    0    0    0    0     ...   0     0    
 [2,]  1   9    1    0    0    0    0    0    0    0     ...   0     0    
 [3,]  0   1    8    1    0    0    0    0    0    0     ...   0     0    
 [4,]  0   0    1    7    1    0    0    0    0    0     ...   0     0    
 [5,]  0   0    0    1    6    1    0    0    0    0     ...   0     0    
 [6,]  0   0    0    0    1    5    1    0    0    0     ...   0     0    
 [7,]  0   0    0    0    0    1    4    1    0    0     ...   0     0    
 [8,]  0   0    0    0    0    0    1    3    1    0     ...   0     0    
 [9,]  0   0    0    0    0    0    0    1    2    1     ...   0     0    
[10,]  0   0    0    0    0    0    0    0    1    1     ...   0     0    
[11,]  0   0    0    0    0    0    0    0    0    1     ...   1     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ...   1     1    
[13,]  0   0    0    0    0    0    0    0    0    0     ...   1     2    
[14,]  0   0    0    0    0    0    0    0    0    0     ...   0     1    
[15,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ...   0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0      0   
 [2,] 0     0     0     0     0     0     0      0   
 [3,] 0     0     0     0     0     0     0      0   
 [4,] 0     0     0     0     0     0     0      0   
 [5,] 0     0     0     0     0     0     0      0   
 [6,] 0     0     0     0     0     0     0      0   
 [7,] 0     0     0     0     0     0     0      0   
 [8,] 0     0     0     0     0     0     0      0   
 [9,] 0     0     0     0     0     0     0      0   
[10,] 0     0     0     0     0     0     0      0   
[11,] 0     0     0     0     0     0     0      0   
[12,] 0     0     0     0     0     0     0      0   
[13,] 1     0     0     0     0     0     0      0   
[14,] 3     1     0     0     0     0     0      0   
[15,] 1     4     1     0     0     0     0      0   
[16,] 0     1     5     1     0     0     0      0   
[17,] 0     0     1     6     1     0     0      0   
[18,] 0     0     0     1     7     1     0      0   
[19,] 0     0     0     0     1     8     1      0   
[20,] 0     0     0     0     0     1     9      1   
[21,] 0     0     0     0     0     0     1     10

In [120]:
eigen(wilkinson)

eigen() decomposition
$values
 [1] 10.7461942 10.7461942  9.2106786  9.2106786  8.0389411  8.0389411
 [7]  7.0039522  7.0039518  6.0002340  6.0002175  5.0002444  4.9997825
[13]  4.0043540  3.9960482  3.0430993  2.9610589  2.1302092  1.7893214
[19]  0.9475344  0.2538058 -1.1254415

$vectors
              [,1]          [,2]          [,3]          [,4]          [,5]
 [1,] 5.495410e-01 -5.493073e-01 -3.824805e-01  3.824543e-01  2.111086e-01
 [2,] 4.100643e-01 -4.098899e-01  3.019000e-01 -3.018793e-01 -4.139963e-01
 [3,] 1.665109e-01 -1.664401e-01  4.460844e-01 -4.460538e-01  1.867663e-01
 [4,] 4.720694e-02 -4.718686e-02  2.381648e-01 -2.381485e-01  4.212692e-01
 [5,] 1.033548e-02 -1.033109e-02  8.042149e-02 -8.041598e-02  2.509076e-01
 [6,] 1.847263e-03 -1.846477e-03  2.004275e-02 -2.004137e-02  9.031667e-02
 [7,] 2.792477e-04 -2.791289e-04  3.972068e-03 -3.971794e-03  2.355942e-02
 [8,] 3.659637e-05 -3.658067e-05  6.544258e-04 -6.543736e-04  4.838449e-03
 [9,] 4.234910e-06 -4.232115e-06  